"""gen_status.py — generate PROJECT_STATUS.md (S5, WO_consolidation-sprint).

A committed, machine-generated snapshot so the vault and the repo look at ONE slice of
truth: the vault no longer has to be the reliable current state. Everything here is derived
from git + the S1 suite registry + the WO checkboxes + results/, so the content is identical
on a fixed commit apart from the `generated_at` timestamp (the S5 gate).

Run:  py scripts/gen_status.py        # writes PROJECT_STATUS.md at the repo root
Called from post-merge.ps1 after a successful pull on main; safe to run by hand.
"""
from __future__ import annotations

import glob
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _git(*args) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                          text=True, encoding="utf-8", errors="replace").stdout.strip()


def _suites() -> dict:
    """The S1 test-suite registry (name -> runner names), imported from verify_all."""
    sys.path.insert(0, os.path.join(ROOT, "Code"))
    import verify_all                                        # import-safe: main() only runs under __main__
    return {name: [m for m, _ in mods] for name, mods in verify_all.SUITES.items()}


def _open_wos() -> list:
    """Every WO_*.md with its checkbox progress; a WO with any unchecked box is OPEN."""
    out = []
    for p in sorted(glob.glob(os.path.join(ROOT, "WO_*.md"))):
        txt = open(p, encoding="utf-8").read()
        total = len(re.findall(r"- \[[ xX]\]", txt))
        done = len(re.findall(r"- \[[xX]\]", txt))
        out.append((os.path.basename(p), done, total))
    return out


def _results() -> list:
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(ROOT, "results", "*.json")))


def main():
    commit = _git("rev-parse", "HEAD")
    short = _git("rev-parse", "--short", "HEAD")
    branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    subject = _git("log", "-1", "--format=%s")
    suites = _suites()
    wos = _open_wos()
    results = _results()
    open_wos = [w for w in wos if w[2] and w[1] < w[2]]

    L = []
    L.append("# PROJECT_STATUS.md")
    L.append("")
    L.append("> Machine-generated by `scripts/gen_status.py` (S5). Do not edit by hand — it is")
    L.append("> regenerated post-merge. One slice of truth for both the repo and the vault.")
    L.append("")
    L.append(f"- **commit**: `{short}` ({commit})")
    L.append(f"- **branch**: `{branch}`")
    L.append(f"- **head**: {subject}")
    L.append(f"- **generated_at**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    L.append("")
    L.append("## Test suites (S1 registry)")
    L.append("")
    L.append("| suite | runners |")
    L.append("|---|---|")
    for name in sorted(suites):
        L.append(f"| `{name}` | {len(suites[name])} |")
    L.append("")
    L.append("The whole claim is `py Code/verify_all.py --suite all`.")
    L.append("")
    L.append("## Work orders")
    L.append("")
    L.append(f"{len(open_wos)} of {len(wos)} WO files carry unchecked checkboxes (checkbox")
    L.append("convention is loose — acceptance is via merge + postscript, not the boxes):")
    L.append("")
    L.append("| WO | checkboxes done |")
    L.append("|---|---|")
    for name, done, total in wos:
        mark = "" if not total else (f"{done}/{total}" + (" ✓" if done == total else ""))
        L.append(f"| `{name}` | {mark or '—'} |")
    L.append("")
    L.append("## Results")
    L.append("")
    if results:
        for r in results:
            L.append(f"- `results/{r}`")
    else:
        L.append("_no `results/*.json` yet (S2 machine-readable output not populated)_")
    L.append("")
    L.append("## Event schema")
    L.append("")
    L.append("- `sim_eventlog.Event` — `(t, kind, scale, where, actor, parent, dm, data)`; "
             "one typed schema for every module. Derived-event provenance fields: see S7.")
    L.append("")

    text = "\n".join(L) + "\n"
    with open(os.path.join(ROOT, "PROJECT_STATUS.md"), "w", encoding="utf-8") as f:
        f.write(text)
    print(f"PROJECT_STATUS.md written ({short}, {len(open_wos)}/{len(wos)} WOs open, "
          f"{len(results)} results).")


if __name__ == "__main__":
    main()
